name: megadetector-pipeline
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch>=2.0.0
      - torchvision>=0.15.0
      - ultralytics>=8.0.0
      - opencv-python>=4.8.0
      - numpy>=1.24.0
      - pillow>=10.0.0
      - tqdm>=4.65.0
      - pyyaml>=6.0.0
      - pathlib2  # for older Python compatibility